/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quizapp.gui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import quizapp.dao.PerformanceDao;
import quizapp.dao.QuestionDao;
import quizapp.pojo.Answer;
import quizapp.pojo.Exam;
import quizapp.pojo.Performance;
import quizapp.pojo.Question;
import quizapp.pojo.UserProfile;
import quizapp.utility.AnswerStore;
import quizapp.utility.QuestionStore;

/**
 *
 * @author hokte
 */
public class TakeTestFrame extends javax.swing.JFrame {

    private Color oldColor;
    private Exam exam;
    private int qno,pos=0;
    private QuestionStore ques;
    private AnswerStore astore;
    
    
    public TakeTestFrame() {
        initComponents();
        setLocationRelativeTo(null);
        oldColor = lblName.getForeground();
        lblName.setText("Hello "+UserProfile.getUsername());
        ques = new QuestionStore();
        astore = new AnswerStore();
        qno=1;
        lblQno.setText(lblQno.getText()+" "+qno);
    }
    public TakeTestFrame(Exam exam){
        this();
        this.exam = exam;
        lblTitle.setText(exam.getLanguage().toUpperCase()+" PAPER");
        loadQuestions();
        showQuestions();
        lblTotalQuestions.setText("Total Questions : "+ques.getSize());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQuestionField = new javax.swing.JTextArea();
        lblQno = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDone = new javax.swing.JButton();
        jrbOption1 = new javax.swing.JRadioButton();
        jrbOption2 = new javax.swing.JRadioButton();
        jrbOption3 = new javax.swing.JRadioButton();
        jrbOption4 = new javax.swing.JRadioButton();
        lblTotalQuestions = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AllProjectIcons/TakeTestIcon.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        lblName.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(153, 255, 0));
        lblName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNameMouseExited(evt);
            }
        });

        lblLogout.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblLogout.setForeground(new java.awt.Color(153, 255, 0));
        lblLogout.setText("Logout");
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(51, 255, 153));

        txtQuestionField.setColumns(20);
        txtQuestionField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        txtQuestionField.setRows(5);
        jScrollPane1.setViewportView(txtQuestionField);

        lblQno.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblQno.setForeground(new java.awt.Color(255, 255, 255));
        lblQno.setText("Que");

        btnNext.setBackground(new java.awt.Color(51, 255, 102));
        btnNext.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(0, 255, 102));
        btnPrevious.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(51, 255, 102));
        btnCancel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDone.setBackground(new java.awt.Color(51, 255, 102));
        btnDone.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        jrbOption1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption1);
        jrbOption1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jrbOption1.setForeground(new java.awt.Color(255, 255, 255));

        jrbOption2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption2);
        jrbOption2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jrbOption2.setForeground(new java.awt.Color(255, 255, 255));

        jrbOption3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption3);
        jrbOption3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jrbOption3.setForeground(new java.awt.Color(255, 255, 255));

        jrbOption4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jrbOption4);
        jrbOption4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jrbOption4.setForeground(new java.awt.Color(255, 255, 255));

        lblTotalQuestions.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        lblTotalQuestions.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(63, 63, 63)
                                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblQno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbOption1)
                                    .addComponent(jrbOption3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jrbOption4)
                                    .addComponent(jrbOption2))
                                .addGap(180, 180, 180)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblTotalQuestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTotalQuestions, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbOption1)
                            .addComponent(jrbOption2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jrbOption3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jrbOption4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrevious)
                            .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lblQno)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseEntered
        lblName.setForeground(Color.CYAN);
    }//GEN-LAST:event_lblNameMouseEntered

    private void lblNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNameMouseExited
        lblName.setForeground(oldColor);
    }//GEN-LAST:event_lblNameMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        int ans = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout ?","Logout?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION){
            LoginScreenFrame fr = new LoginScreenFrame();
            fr.setVisible(true);
            this.dispose();
        }
        return;
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setForeground(Color.CYAN);
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setForeground(oldColor);
    }//GEN-LAST:event_lblLogoutMouseExited

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
       String chosenAnswer = getUserAnswer();
       if(chosenAnswer!=null){
           Question quest = ques.getQuestionByQno(qno);
           String correctAnswer = quest.getCorrect_answer();
           Answer ans = new Answer(exam.getExamid(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted = astore.getAnswerByQno(qno);
           if(attempted==null){
               astore.addAnswer(ans);
           }
           else{
               String prevAnswer = attempted.getChosenAnswer();
               if(prevAnswer.equals(chosenAnswer)==false){
                   int apos = astore.removeAnswer(attempted);
                   astore.setAnswerAt(apos, ans);
               }
           }
           pos++;
        if(pos>=ques.getSize()){
            pos=0;
        }
        qno++;
        if(qno>ques.getSize()){
            JOptionPane.showMessageDialog(null,"You are done with all the questions , if you have still remains with some questions which are unattempted , kindly attempt that or to submit the test , CLICK on DONE button !! ");
            qno=1;
        }
        lblQno.setText("Que "+qno);
        showQuestions();
       }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        String chosenAnswer = getUserAnswer();
       if(chosenAnswer!=null){
           Question quest = ques.getQuestionByQno(qno);
           String correctAnswer = quest.getCorrect_answer();
           Answer ans = new Answer(exam.getExamid(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted = astore.getAnswerByQno(qno);
           if(attempted==null){
               astore.addAnswer(ans);
           }
           else{
               String prevAnswer = attempted.getChosenAnswer();
               if(prevAnswer.equals(chosenAnswer)==false){
                   int apos = astore.removeAnswer(attempted);
                   astore.setAnswerAt(apos, ans);
               }
           }
           pos--;
        if(pos<0){
            pos=ques.getSize()-1;
        }
        qno--;
        if(qno<=0){
            qno=ques.getSize();
        }
        lblQno.setText("Que "+qno);
        showQuestions();
       }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int ans = JOptionPane.showConfirmDialog(null, "Are you sure you want to Quit the exam before completing the exam?","Are you Sure?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(ans==JOptionPane.YES_OPTION){
            PaperSelectionFrame fr = new PaperSelectionFrame();
            fr.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        if(qno!=ques.getSize()){
            int sure = JOptionPane.showConfirmDialog(null, "You are remains with some more questions in your test !! , still you wants to submit the test \nClick on Yes if you want to submit the test\nOtherwise click on Next button to solve the next question !!","Are you sure?",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(sure==JOptionPane.NO_OPTION) return;
        }
        String chosenAnswer = getUserAnswer();
        if(chosenAnswer!=null){
           Question quest = ques.getQuestionByQno(qno);
           String correctAnswer = quest.getCorrect_answer();
           Answer ans = new Answer(exam.getExamid(),exam.getLanguage(),qno,chosenAnswer,correctAnswer);
           Answer attempted = astore.getAnswerByQno(qno);
           if(attempted==null){
               astore.addAnswer(ans);
           }
           else{
               String prevAnswer = attempted.getChosenAnswer();
               if(prevAnswer.equals(chosenAnswer)==false){
                   int apos = astore.removeAnswer(attempted);
                   astore.setAnswerAt(apos, ans);
               }
           }
       }
       
       int right=0,wrong=0;
       for(Question quest:ques.getAllQuestions()){
           int qno = quest.getQno();
           Answer ans = astore.getAnswerByQno(qno);
           if(ans==null) continue;
           String attemptedAnswer = ans.getChosenAnswer();
           String correctAnswer = ans.getCorrectAnswer();
           if(attemptedAnswer.equals(correctAnswer)) ++right;
           else ++wrong;
       }
       
       StringBuilder sb = new StringBuilder();
       sb.append("Right answers : "+right);
       sb.append("\nWrong answers : "+wrong);
       sb.append("\nUnattempted answers : "+(ques.getSize()-(right+wrong)));
       JOptionPane.showMessageDialog(null,sb.toString(),"Result !",JOptionPane.INFORMATION_MESSAGE);
       double per = (double)right/ques.getSize()*100.0;
       try{
           Performance perf = new Performance(UserProfile.getUsername(),exam.getExamid(),right,wrong,(ques.getSize()-(right+wrong)),per,exam.getLanguage());
           PerformanceDao.addPerformance(perf);
           JOptionPane.showMessageDialog(null,"Result Saved!!\nThankyou for the test","Done !!",JOptionPane.INFORMATION_MESSAGE);
           StudentOptionsFrame fr = new StudentOptionsFrame();
           fr.setVisible(true);
           this.dispose();
       }
       catch(SQLException ex){
          JOptionPane.showMessageDialog(null,"DB Error , In Take Test Frame","Error !!",JOptionPane.ERROR_MESSAGE);
          ex.printStackTrace();
       }
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TakeTestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TakeTestFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrbOption1;
    private javax.swing.JRadioButton jrbOption2;
    private javax.swing.JRadioButton jrbOption3;
    private javax.swing.JRadioButton jrbOption4;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblQno;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotalQuestions;
    private javax.swing.JTextArea txtQuestionField;
    // End of variables declaration//GEN-END:variables

    private void loadQuestions() {
        try{
             ArrayList<Question>que = QuestionDao.getQuestionsByExamId(exam.getExamid());
             for(Question q:que){
                 ques.addQuestion(q);
             }
             System.out.print(ques);
         }
         catch(SQLException ex){
             JOptionPane.showMessageDialog(null, "Error in getting questions from the database !!","Error",JOptionPane.ERROR_MESSAGE);
             ex.printStackTrace();
         }
    }

    private void showQuestions() {
        Question q = ques.getQuestion(pos);
        buttonGroup1.clearSelection();
        txtQuestionField.setText(q.getQuestion());
        jrbOption1.setText(q.getAnswer1());
        jrbOption2.setText(q.getAnswer2());
        jrbOption3.setText(q.getAnswer3());
        jrbOption4.setText(q.getAnswer4());
        Answer ans = astore.getAnswerByQno(qno);
        if(ans==null) return;
        String str = ans.getChosenAnswer();
        switch(str){
            case "ANSWER1":
                jrbOption1.setSelected(true);
                break;
            case "ANSWER2":
                jrbOption2.setSelected(true);
                break;
            case "ANSWER3":
                jrbOption3.setSelected(true);
                break;
            case "ANSWER4":
                jrbOption4.setSelected(true);
                break;
        }
    }
    
    private String getUserAnswer(){
        if(jrbOption1.isSelected()) return "ANSWER1";
        else if(jrbOption2.isSelected()) return "ANSWER2";
        else if(jrbOption3.isSelected()) return "ANSWER3";
        else if(jrbOption4.isSelected()) return "ANSWER4";
        else return null;
    }
}
